SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds

SHOT_RADIUS = 5

EXPLOSION_PARTICLE_DURATION = 2  # seconds


SHIELD_DURATION = 60  # seconds
SHIELD_RADIUS = 30
SHIELD_WIDTH = 5
SHIELD_SPAWN_RATE = 15  # seconds
SHIELD_COLOR = (255, 255, 255)

POWER_UP_SIZE = (40, 40)
